==== Download-Service auf Basis von OGC API Features.
===== Einleitung

OGC API - Features bietet API-Bausteine zum Erstellen, Bearbeiten und Abfragen von Entitäten im Web. OGC API - Features besteht aus mehreren Teilen, von denen jeder einen eigenen Standard darstellt. Der Teil http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[`Core`] legt die grundlegenden Fähigkeiten fest und beschränkt sich auf das Abrufen von Entitäten, deren Geometrien im Koordinatenreferenzsystem WGS 84 mit einer Achsenordnung Länge/Breite dargestellt werden. 

===== Anforderungsklassen
====== Anforderungsklasse

[width="100%",cols="50%,50%",options="noheader",]
|===
|*Anforderungsklasse*
|https://ech.ch/fr/0056/main/oafeat/req/oafeat
|Zieltyp |Web API
|Abhängigkeiten|https://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 1: Core] +
https://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API - Features - Part 2: Coordinate Reference Systems by Reference]
|===

[width="100%",cols="24%,76%",options="noheader",]
|===
|*Richtlinie 1* |/req/oafeat/links
|A |Die Landingpage *MUSS* einen Link `rel=describedby` enthalten, der auf maschinenlesbare Dienstmetadaten nach dem GM03-Modell Version 2.1 [13] verweist.
|B |Jede Collection *MUSS* einen Link mit `rel=describedbyby` enthalten, der auf maschinenlesbare Datenmetadaten gemäss Vorlage GM03 Version 2.1 [13] verweist. + 
Für den modellkonformen Austausch von Vektordaten *MUSS*, sofern verfügbar, eine INTERLIS XTF [7] oder INTERLIS GML [8] Ressource angeboten werden.
|===

[width="100%",cols="24%,76%",options="noheader",]
|===
|*Empfehlung 1* |/rec/oafeat/links
|A | Jede Collection *SOLLTE* einen Link mit `rel=enclosure enthalten, der auf einen Bulk-Download des Datensatzes verweist (z. B. ein STAC-Asset). 
|===
