==== Darstellungsdienst basierend auf OGC API Tiles
==== Einleitung

Der Standard OGC API - Tiles definiert die grundlegenden Elemente für die Erstellung von Web-APIs, die den Abruf von Geoinformationen in Form von Tiles unterstützen. Es werden verschiedene Formen von Geoinformationen unterstützt, z. B. Vektor- und Rasterkacheln sowie andere Arten von Geoinformationen. 

Obwohl der OGC API-Standard - Tiles unabhängig verwendet werden kann, kann er mit anderen OGC API-Standards und Spezifikationsprojekten kombiniert werden, um zusätzliche Fähigkeiten zu erhalten oder die Interoperabilität für bestimmte Datentypen zu erhöhen.

Der OGC API-Standard - Tiles bezieht sich auf den OGC-Standard Two Dimensional Tile Matrix Set (TMS) and Tileset Metadata, der logische Modelle und Kodierungen zur Spezifizierung von Tile-Matrix-Sets und zur Beschreibung von Tile-Sets definiert. Ein Tile-Matrix-Set ist ein Tile-Schema, das es einer Anwendung ermöglicht, den Raum anhand eines Satzes regelmäßiger Raster, die für mehrere Maßstäbe in einem Referenzkoordinatensystem (CRS) definiert sind, zu partitionieren und zu indizieren.

==== Anforderungsklassen
===== OGC-Anforderungsklasse API Tiles Core

[width="100%",cols="24%,76%",options="header",]
|===
|*Anforderungsklasse* |https://ech.ch/fr/0056/main/oat/req/oat/encodings
|Zieltyp |Web API
| Abhängigkeiten |https://docs.ogc.org/is/20-057/20-057.html#toc65[OGC API - Tiles - Part 1: Core + Requirements Classes for tile encodings]
|===

[width="100%",cols="24%,76%",options="header",]
|===
|*Anforderung 1* |/req/oat/encodings
|A |Die Umsetzung einer OGC API API Tiles MUSS das Bildformat *JPEG* unterstützen.
|B |Die Umsetzung einer OGC API Tiles API MUSS das Bildformat  *PNG* unterstützen.
|B |Die Umsetzung einer OGC API API Tiles MUSS das Bildformat *GeoJSON* für Vektorkacheln unterstützen.
|C |Die OGC API Tiles API-Implementierung MUSS das Bildformat *TIFF* für Rasterkacheln unterstützen.
|===