[.appendix nonumber]
== Annexe E – Nouvelles tendances en matière de géostandards

La recherche, l'accès et l'utilisation de données géographiques diffusées par des infrastructures de données géographiques (IDG) basées sur les OGC Web Service Standards (WMS, WFS, WCS, WPS, etc.) présentent certains inconvénients : Ces ne sont en principe pas adaptés à l'indexation de leur contenu par les moteurs de recherche (les données sont introuvables sur le web) et sont difficiles à utiliser pour les utilisateurs non spécialisés.
Fort de ce constat, l'Open Geospatial Consortium s'est associé au W3C, pour produire le document https://www.w3.org/TR/sdw-bp[«Spatial Data on the Web Best Practices»] Ce document donne des conseils sur les meilleures pratiques liées à la publication de données spatiales sur le Web et à l'utilisation des technologies Web dans le domaine de la localisation. Ces recommandations sont destinées aux praticiens, y compris les développeurs Web et les experts géospatiaux, et sont compilées sur la base de preuves d'application dans le monde réel. Ces bonnes pratiques suggèrent un changement d'orientation significatif par rapport aux infrastructures de données spatiales traditionnelles en adoptant une approche basée sur les normes générales du Web. La localisation étant souvent le facteur commun à plusieurs ensembles de données, les données spatiales constituent un complément particulièrement utile au Web de données.
Sur la base de cette expérience, l'Open Geospatial Consortium a commencé à développer une nouvelle famille de normes : les https://ogcapi.ogc.org[OGC API]. Ces nouveaux standards doivent permettre à chacun de fournir et d'utiliser facilement des données géographiques sur le web et d'intégrer ces données avec tout autre type d'information. Ces normes définissent des API centrées sur les ressources, qui tirent profit des techniques modernes de développement web.
Les API de l'OGC sont conçues pour que N'IMPORTE QUI puisse facilement fournir et utiliser des données géospatiales sur le web, et intégrer ces données à n'importe quel autre type d'information. Ces normes s'appuient sur l'héritage des normes de services Web de l'OGC (WMS, WFS, WCS, WPS, etc.), mais définissent des API centrées sur les ressources qui tirent parti des pratiques modernes de développement Web.
A la différence des OGC Web Service Standards, les API de l'OGC se base sur une API Rest et non plus sur le protocole SOAP. Elles privilégient l'encoding JSON au XML qui lui est moins verbeux et plus facilement compréhensible. Elles sont, de plus, assorties d'une documentation basée sur la spécification OpenAPI pour favoriser leur découverte et intégration, de même que d'un rendu HTML et de endpoints en JSON-LD pour favoriser leur indexation dans les moteurs de recherche.
Ces normes sont également conçues comme des "Building Blocks" pouvant être utilisés pour assembler de nouvelles API pour l'accès au contenu géospatial sur le web. Les modules sont définis non seulement par les exigences des normes spécifiées dans le programme de normes de l'OGC, mais aussi par le prototypage et l'essai d'interopérabilité dans le cadre du programme de solutions collaboratives et d'innovation de l'OGC.
Les données géospatiales optimisées pour le cloud sont de plus en plus populaires alors que les entreprises transfèrent leurs charges de travail vers le cloud computing. Plutôt que de simplement héberger les données existantes dans le nuage, de nombreuses organisations conçoivent désormais des solutions de stockage de données géospatiales spécifiquement pour les environnements cloud. Cela leur permet de bénéficier des avantages en termes d'évolutivité et de performances qu'offre le cloud computing. Avec l'augmentation de la disponibilité des flux de données en temps réel provenant de sources telles que l'imagerie satellite et les capteurs IoT, de nombreuses organisations cherchent des moyens de traiter rapidement et efficacement ces données dans le cloud. L'informatique sans serveur offre la possibilité d'exécuter du code sans avoir besoin de gérer et de provisionner des serveurs, ce qui est particulièrement utile pour le traitement des données géospatiales. Cela permet aux organisations d'ajuster facilement leur puissance de traitement en fonction de la demande. Enfin, l'IA et le ML sont de plus en plus utilisés pour analyser les données géospatiales dans le cloud, notamment pour la détection d'objets, la classification et la modélisation prédictive.
Ces nouvelles pratiquent orientent donc la création de nouveaux standards de géodonnées tels que COG, STAC, Zarr, COPC, GeoParquet et Flatgeobuff émergent, et le présent document émet des recommandations à leur sujet.
